spring.application.name=MCPPOC-1
server.port=8080
spring.data.mongodb.uri=mongodb://localhost:27017/mcpdb
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
logging.level.org.springframework=INFO
spring.ai.ollama.chat.options.functions=createEmployee,getAllEmployees,getEmployee,updateEmployee,deleteEmployee
logging.level.org.springframework.ai=DEBUG